import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class addQues extends javax.swing.JFrame {

    /**
     * Creates new form addQues
     */
    public addQues() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            PreparedStatement ps=connection.prepareStatement("select count(Id) from add_question");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                int Id=rs.getInt(1);
                Id=Id+1;
                String str=String.valueOf(Id);
                idLabel.setText(str);
            }
            else
                idLabel.setText("1");
            
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        questionField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        opt1Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        opt2Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        opt3Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        opt4Field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        idLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(176, 173, 22));
        jLabel2.setText("Question ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, 35));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(176, 173, 22));
        jLabel3.setText("Question :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 262, 124, 35));
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 262, 772, 35));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(176, 173, 22));
        jLabel4.setText("Option 1 :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 308, 124, 35));
        getContentPane().add(opt1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 308, 772, 35));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(176, 173, 22));
        jLabel5.setText("Option 2 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 354, 124, 35));
        getContentPane().add(opt2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 354, 772, 35));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(176, 173, 22));
        jLabel6.setText("Option 3 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 400, 124, 35));

        opt3Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3FieldActionPerformed(evt);
            }
        });
        getContentPane().add(opt3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 400, 772, 35));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(176, 173, 22));
        jLabel7.setText("Option 4 :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 446, 124, 35));
        getContentPane().add(opt4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 446, 772, 35));

        jButton1.setBackground(new java.awt.Color(255, 189, 89));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 153, 102));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back btn ad qs.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1255, 0, 110, 50));

        jButton2.setBackground(new java.awt.Color(255, 189, 89));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save btn ad qs.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 570, 110, 50));

        jButton3.setBackground(new java.awt.Color(255, 189, 89));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear add qs.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 110, 50));

        idLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        idLabel.setForeground(new java.awt.Color(176, 173, 22));
        idLabel.setText("00");
        idLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idLabelMouseClicked(evt);
            }
        });
        getContentPane().add(idLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 219, 104, 35));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(176, 173, 22));
        jLabel8.setText("Answer :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 490, 120, 35));
        getContentPane().add(answerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 772, 35));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add qs background.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt3FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3FieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String Id=idLabel.getText();
            String Name=questionField.getText();
            String Opt1=opt1Field.getText();
            String Opt2=opt2Field.getText();
            String Opt3=opt3Field.getText();
            String Opt4=opt4Field.getText();
            String Answer=answerField.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=connection.createStatement();
            st.executeUpdate("insert into add_question(Id,Name,Opt1,Opt2,Opt3,opt4,Answer) values('"+Id+"','"+Name+"','"+Opt1+"','"+Opt2+"','"+Opt3+"','"+Opt4+"','"+Answer+"')");
            
            if(questionField.getText().length()<=0||opt1Field.getText().length()<=0||opt2Field.getText().length()<=0||opt3Field.getText().length()<=0||opt4Field.getText().length()<=0||answerField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Every TextBox must conatin Some Value!!");
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Congratulations , Question pass has been added!!");
            setVisible(false);
            new addQues().setVisible(true);
            }
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong!!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminHome().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        questionField.setText("");
        opt1Field.setText("");
        opt2Field.setText("");
        opt3Field.setText("");
        opt4Field.setText("");
        answerField.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void idLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_idLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addQues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addQues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addQues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addQues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addQues().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField opt1Field;
    private javax.swing.JTextField opt2Field;
    private javax.swing.JTextField opt3Field;
    private javax.swing.JTextField opt4Field;
    private javax.swing.JTextField questionField;
    // End of variables declaration//GEN-END:variables
}
