import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class addWord extends javax.swing.JFrame {

    /**
     * Creates new form addWord
     */
    public addWord() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            PreparedStatement ps=connection.prepareStatement("select count(WId) from word");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                int WId=rs.getInt(1);
                WId=WId+1;
                String str=String.valueOf(WId);
                widLabel.setText(str);
            }
            else
                widLabel.setText("1");
            
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wordField = new javax.swing.JTextField();
        widLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        meaningField = new javax.swing.JTextField();
        topicsField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(wordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 780, 36));

        widLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        widLabel.setText("00");
        getContentPane().add(widLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 39, 40));

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/save btn ad wrd.png"))); // NOI18N
        saveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, 110, 50));

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clear btn ad wrd.png"))); // NOI18N
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 580, 110, 50));

        jButton5.setBackground(new java.awt.Color(251, 227, 4));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back btn ad wrd.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1275, 0, 90, 40));

        meaningField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meaningFieldActionPerformed(evt);
            }
        });
        getContentPane().add(meaningField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 780, 100));

        topicsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topicsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(topicsField, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 780, 70));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setText("Word ID :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 100, 30));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel3.setText("Word :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 90, 40));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setText("Meaning :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 100, 30));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel5.setText("Topics Related :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UDS oper bckgrd.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try{
            String WId=widLabel.getText();
            String WordName=wordField.getText();
            String Meaning=meaningField.getText();
            String Topics=topicsField.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=connection.createStatement();
            st.executeUpdate("insert into word(WId,WordName,Meaning,Topics) values('"+WId+"','"+WordName+"','"+Meaning+"','"+Topics+"')");
            if(wordField.getText().length()<=0||meaningField.getText().length()<=0||topicsField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Every TextBox must conatin Some Value!!");
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Word added successfully!!");
            
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong!!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        wordField.setText("");
        meaningField.setText("");
        topicsField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminHome().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void topicsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topicsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topicsFieldActionPerformed

    private void meaningFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meaningFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_meaningFieldActionPerformed

    private void wordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addWord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addWord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField meaningField;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField topicsField;
    private javax.swing.JLabel widLabel;
    private javax.swing.JTextField wordField;
    // End of variables declaration//GEN-END:variables
}
