import java.awt.event.ItemEvent;
import java.sql.*;

import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class getdoorpass extends javax.swing.JFrame {

   
    public getdoorpass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        lastNamefield = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        mobileLabel = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        StateField = new javax.swing.JLabel();
        stateComboBox = new javax.swing.JComboBox<>();
        countryLabel = new javax.swing.JLabel();
        countryComboBox = new javax.swing.JComboBox<>();
        createPasswordLabel = new javax.swing.JLabel();
        createPasswordField = new javax.swing.JPasswordField();
        usernameLabel = new javax.swing.JLabel();
        answerField = new javax.swing.JTextField();
        getPassbutton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        usernameField = new javax.swing.JTextField();
        passwordCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        securityComboBox = new javax.swing.JComboBox<>();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        firstNameLabel.setText("First Name :");
        getContentPane().add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, 30));

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 152, 30));

        LastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LastNameLabel.setText("Last Name :");
        getContentPane().add(LastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 76, 30));

        lastNamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(lastNamefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 152, 30));

        genderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        genderLabel.setText("Gender :");
        getContentPane().add(genderLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 90, 30));

        mobileLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mobileLabel.setText("Mobile No. :");
        getContentPane().add(mobileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 90, 30));

        mobileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileFieldActionPerformed(evt);
            }
        });
        getContentPane().add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 450, 30));

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        emailLabel.setText("Email:");
        getContentPane().add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 289, 90, 30));

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 289, 450, 30));

        StateField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        StateField.setText("State:");
        getContentPane().add(StateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 359, 90, 30));

        stateComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttarakhand", "Uttar Pradesh", "West Bengal" }));
        stateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(stateComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 359, 150, 30));

        countryLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        countryLabel.setText("Country :");
        getContentPane().add(countryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 71, 30));

        countryComboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "India" }));
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(countryComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 360, 180, 30));

        createPasswordLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        createPasswordLabel.setText("Create Password :");
        getContentPane().add(createPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 120, 30));

        createPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPasswordFieldActionPerformed(evt);
            }
        });
        getContentPane().add(createPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 310, 310, 30));

        usernameLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        usernameLabel.setText("Username :");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 240, 120, 30));

        answerField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerFieldActionPerformed(evt);
            }
        });
        getContentPane().add(answerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 450, 30));

        getPassbutton.setBackground(new java.awt.Color(213, 100, 213));
        getPassbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getPassbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/get pass button.png"))); // NOI18N
        getPassbutton.setBorder(null);
        getPassbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getPassbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPassbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(getPassbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, 150, 50));

        backButton.setBackground(new java.awt.Color(243, 91, 132));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cross get pass.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1326, 0, 40, 40));

        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 240, 310, 30));

        passwordCheckBox.setText("show Password");
        passwordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(passwordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 360, 120, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 100, -1));

        securityComboBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        securityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Security Question", "Which was your first school ?", "Which is your favourite place ? ", "Which is your favourite book ?" }));
        securityComboBox.setBorder(null);
        securityComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                securityComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(securityComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 580, 30));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 450, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Answer :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, -1, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/get pass.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateComboBoxActionPerformed

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxActionPerformed

    private void getPassbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPassbuttonActionPerformed
        // TODO add your handling code here:
        try{
            String FirstName=firstNameField.getText();
            String LastName=lastNamefield.getText();
            String Gender=(String)genderComboBox.getSelectedItem();
            String MobileNumber=mobileField.getText();
            String Email=emailField.getText();
            String State=(String)stateComboBox.getSelectedItem();
            String Country=(String)countryComboBox.getSelectedItem();
            String Password=createPasswordField.getText();
            String Username=usernameField.getText();
            String SecurityQuestion=(String)securityComboBox.getSelectedItem();
            String Answer=answerField.getText();
            
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=con.createStatement();
            st.executeUpdate("insert into getpass(FirstName,LastName,Gender,MobileNumber,Email,State,Country,Password,Username,SecurityQuestion,Answer) values('"+FirstName+"','"+LastName+"','"+Gender+"','"+MobileNumber+"','"+Email+"','"+State+"','"+Country+"','"+Password+"','"+Username+"','"+SecurityQuestion+"','"+Answer+"')");
            if(firstNameField.getText().length()<=0||lastNamefield.getText().length()<=0||mobileField.getText().length()<=0||createPasswordField.getText().length()<=0||usernameField.getText().length()<=0||answerField.getText().length()<=0||genderComboBox.getSelectedIndex()<0||stateComboBox.getSelectedIndex()<0||countryComboBox.getSelectedIndex()<0||securityComboBox.getSelectedIndex()<0)
            {
               JOptionPane.showMessageDialog(null,"Enter values properly in eact TextBOX!!");
            }
            else
            {
            JOptionPane.showMessageDialog(null,"Congratulations , Your pass has been created Successfully!!");
            setVisible(false);
            new quizerlogin().setVisible(true);
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Fill the details appropriately! TRY AGAIN !!");
        }
    }//GEN-LAST:event_getPassbuttonActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNamefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNamefieldActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void createPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPasswordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void securityComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_securityComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_securityComboBoxActionPerformed

    private void answerFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerFieldActionPerformed

    private void mobileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new quizerlogin().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void passwordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(passwordCheckBox.isSelected())
        {
           createPasswordField.setEchoChar((char)0); 
        }
        else
        {
            createPasswordField.setEchoChar('•');
        }
    }//GEN-LAST:event_passwordCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getdoorpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel StateField;
    private javax.swing.JTextField answerField;
    private javax.swing.JButton backButton;
    private javax.swing.JComboBox<String> countryComboBox;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JPasswordField createPasswordField;
    private javax.swing.JLabel createPasswordLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JButton getPassbutton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lastNamefield;
    private javax.swing.JTextField mobileField;
    private javax.swing.JLabel mobileLabel;
    private javax.swing.JCheckBox passwordCheckBox;
    private javax.swing.JComboBox<String> securityComboBox;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
