
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class participantForm extends javax.swing.JFrame {

    /**
     * Creates new form participantForm
     */
    public participantForm() {
        initComponents();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            PreparedStatement ps=connection.prepareStatement("select count(PId) from participant");
            ResultSet rs = ps.executeQuery();
            if(rs.next())
            {
                int PId=rs.getInt(1);
                PId=PId+1;
                String str=String.valueOf(PId);
                pidLabel.setText(str);
            }
            else
                pidLabel.setText("1");
            
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pidLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        occupField = new javax.swing.JTextField();
        qualField = new javax.swing.JTextField();
        doneButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pidLabel.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        pidLabel.setText("00");
        getContentPane().add(pidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 140, 40));

        nameField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 560, 30));

        occupField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        getContentPane().add(occupField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 460, 30));

        qualField.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        qualField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qualFieldActionPerformed(evt);
            }
        });
        getContentPane().add(qualField, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 420, 30));

        doneButton.setBackground(new java.awt.Color(255, 255, 255));
        doneButton.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        doneButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/submit btn participant form.png"))); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 500, 100, 42));

        backButton.setBackground(new java.awt.Color(255, 255, 255));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back btn participant form.png"))); // NOI18N
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1265, 0, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/participant bckgrd.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qualFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qualFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qualFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new quizerHome().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        // TODO add your handling code here:
        try{
            String PId=pidLabel.getText();
            String Name=nameField.getText();
            String Occupation=occupField.getText();
            String Qualification=qualField.getText();
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=connection.createStatement();
            st.executeUpdate("insert into participant(PId,Name,Occupation,Qualification) values('"+PId+"','"+Name+"','"+Occupation+"','"+Qualification+"')");
            if(nameField.getText().length()<=0||occupField.getText().length()<=0||qualField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Enter every value properly!!");
            }
            else
            {
            JOptionPane.showMessageDialog(null,"FORM SUCCESSFULLY SUBMITTED!!");
            setVisible(false);
            new instructStart().setVisible(true);
            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Something went wrong!!");
        }
    }//GEN-LAST:event_doneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(participantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(participantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(participantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(participantForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new participantForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField occupField;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextField qualField;
    // End of variables declaration//GEN-END:variables
}
