import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class quesOperations extends javax.swing.JFrame {

    /**
     * Creates new form quesOperations
     */
    public quesOperations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        opt1Field = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        opt2Field = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        opt3Field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        opt4Field = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        questionField = new javax.swing.JTextField();
        answerField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(100, 76, 4));
        jLabel1.setText("Question ID :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 160, 170, 38));

        idField.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 164, 460, 38));

        searchButton.setBackground(new java.awt.Color(244, 241, 241));
        searchButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(100, 76, 4));
        searchButton.setText("SEARCH");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 164, 120, 38));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(100, 76, 4));
        jLabel3.setText("Question :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 220, 160, 38));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(100, 76, 4));
        jLabel4.setText("Option 1 :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 314, 160, 38));

        opt1Field.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(opt1Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 314, 460, 38));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(100, 76, 4));
        jLabel5.setText("Option 2 :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 370, 160, 38));

        opt2Field.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(opt2Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 370, 460, 38));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(100, 76, 4));
        jLabel6.setText("Option 3 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 426, 160, 38));

        opt3Field.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(opt3Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 426, 460, 38));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(100, 76, 4));
        jLabel7.setText("Option 4 : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 482, 160, 37));

        opt4Field.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(opt4Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 482, 460, 37));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(100, 76, 4));
        jLabel8.setText("Answer :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 537, 160, 38));

        updateButton.setBackground(new java.awt.Color(244, 241, 241));
        updateButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(100, 76, 4));
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 570, -1, 40));

        deleteButton.setBackground(new java.awt.Color(244, 241, 241));
        deleteButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(100, 76, 4));
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 570, 112, 40));

        jButton4.setBackground(new java.awt.Color(244, 241, 241));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(100, 76, 4));
        jButton4.setText("BACK");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        questionField.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(questionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 220, 460, 80));

        answerField.setBackground(new java.awt.Color(244, 241, 241));
        getContentPane().add(answerField, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 540, 460, 90));

        clearButton.setBackground(new java.awt.Color(244, 241, 241));
        clearButton.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        clearButton.setForeground(new java.awt.Color(100, 76, 4));
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 220, 120, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ques operate backgrd.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminHome().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        String Id=idField.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=connection.createStatement();
            ResultSet rs=st.executeQuery("select *from add_question where Id='"+Id+"'");
            if(rs.next())
            {
                questionField.setText(rs.getString(2));
                opt1Field.setText(rs.getString(3));
                opt2Field.setText(rs.getString(4));
                opt3Field.setText(rs.getString(5));
                opt4Field.setText(rs.getString(6));
                answerField.setText(rs.getString(7));
                
            }
            else if(idField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Please enter some value in ID Box!!");
            }
            else
            {
                JFrame jf=new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf,"Question Id does not exist");
            }
        }
        catch(Exception e)
        {
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,e);
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String Id=idField.getText();
        String newName=questionField.getText();
        String newOpt1=opt1Field.getText();
        String newOpt2=opt2Field.getText();
        String newOpt3=opt3Field.getText();
        String newOpt4=opt4Field.getText();
        String newAnswer=answerField.getText();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select *from add_question where Id='"+Id+"'");
            if(rs.next())
            {
                 st.executeUpdate("update add_question set Name='"+newName+"' where Id='"+Id+"'");
                 st.executeUpdate("update add_question set Opt1='"+newOpt1+"' where Id='"+Id+"'");
                 st.executeUpdate("update add_question set Opt2='"+newOpt2+"' where Id='"+Id+"'");
                 st.executeUpdate("update add_question set Opt3='"+newOpt3+"' where Id='"+Id+"'");
                 st.executeUpdate("update add_question set Opt4='"+newOpt4+"' where Id='"+Id+"'");
                 st.executeUpdate("update add_question set Answer='"+newAnswer+"' where Id='"+Id+"'");
                 JOptionPane.showMessageDialog(null,"Question successfully Updated!!");
                 setVisible(false);
                 new quesOperations().setVisible(true);
            }
            else if(idField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Please enter some value in ID Box!!");
            }
             else
                 JOptionPane.showMessageDialog(null,"Incorrect values entered!!");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Connection Error!!!");
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        idField.setText("");
        questionField.setText("");
        opt1Field.setText("");
        opt2Field.setText("");
        opt3Field.setText("");
        opt4Field.setText("");
        answerField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        String Id=idField.getText();
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            PreparedStatement ps=con.prepareStatement("delete from add_question where Id=?");
            ps.setString(1, Id);
            ps.executeUpdate();
            JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            if(idField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Please enter some value in ID Box!!");
            }
            else
            {
            JOptionPane.showMessageDialog(jf, "Successfully Deleted");
            }
            
        }
        catch(Exception e)
        {
           JFrame jf=new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf,e); 
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quesOperations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quesOperations().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField idField;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField opt1Field;
    private javax.swing.JTextField opt2Field;
    private javax.swing.JTextField opt3Field;
    private javax.swing.JTextField opt4Field;
    private javax.swing.JTextField questionField;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
