import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class quizerlogin extends javax.swing.JFrame {

   
    public quizerlogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        doorInButton = new javax.swing.JButton();
        getPassButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        passwordCheckBox = new javax.swing.JCheckBox();
        forgotButton = new javax.swing.JButton();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizer login.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doorInButton.setBackground(new java.awt.Color(153, 0, 153));
        doorInButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doorInButton.setForeground(null);
        doorInButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/door in button.png"))); // NOI18N
        doorInButton.setBorder(null);
        doorInButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doorInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doorInButtonActionPerformed(evt);
            }
        });
        getContentPane().add(doorInButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 140, 50));

        getPassButton.setFont(new java.awt.Font("Calibri Light", 2, 18)); // NOI18N
        getPassButton.setForeground(new java.awt.Color(255, 255, 255));
        getPassButton.setText("Click here to make a door Pass  !!");
        getPassButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), null, null, new java.awt.Color(153, 153, 153)));
        getPassButton.setContentAreaFilled(false);
        getPassButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getPassButtonActionPerformed(evt);
            }
        });
        getContentPane().add(getPassButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 589, 250, 50));

        backButton.setBackground(new java.awt.Color(173, 116, 212));
        backButton.setForeground(null);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back button quizer login.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 50));

        passwordCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        passwordCheckBox.setText("Show Password");
        passwordCheckBox.setBorder(null);
        passwordCheckBox.setBorderPainted(true);
        passwordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(passwordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, -1, -1));

        forgotButton.setText("Forgot Password ");
        forgotButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), null, null, new java.awt.Color(153, 153, 153)));
        forgotButton.setContentAreaFilled(false);
        forgotButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotButtonActionPerformed(evt);
            }
        });
        getContentPane().add(forgotButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 110, 20));

        usernameLabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(153, 0, 153));
        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter username.png"))); // NOI18N
        usernameLabel.setText("Username");
        getContentPane().add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 28));

        passwordLabel.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(153, 0, 153));
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enter password.png"))); // NOI18N
        passwordLabel.setText("Password");
        getContentPane().add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 110, 28));

        usernameField.setBorder(null);
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 180, 220, 28));

        passwordField.setBorder(null);
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 240, 220, 28));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quizer login.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 108, 230), 15));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getPassButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new getdoorpass().setVisible(true);
    }//GEN-LAST:event_getPassButtonActionPerformed

    private void doorInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doorInButtonActionPerformed
        // TODO add your handling code here:
            String Username=usernameField.getText();
            String Password=passwordField.getText();
            try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/technicalshow","root","Aman.komal2122");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("Select *from getpass where Username='"+Username+"' and Password='"+Password+"'");
            
            if(usernameField.getText().length()<=0||passwordField.getText().length()<=0)
            {
                JOptionPane.showMessageDialog(null,"Values must be entered in every Text Box!!!");
            }
            else if(rs.next())
            {
                setVisible(false);
                new quizerHome().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Wrong Password!!!");
            }    
        }    
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error in Connection!!!");
        }
        
    }//GEN-LAST:event_doorInButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void passwordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordCheckBoxActionPerformed
        // TODO add your handling code here:
        if(passwordCheckBox.isSelected())
        {
            passwordField.setEchoChar((char)0);
        }
        else
        {
            passwordField.setEchoChar('•');
        }
        
    }//GEN-LAST:event_passwordCheckBoxActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void forgotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new forgotpassword().setVisible(true);
    }//GEN-LAST:event_forgotButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getdoorpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quizerlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton doorInButton;
    private javax.swing.JButton forgotButton;
    private javax.swing.JButton getPassButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JCheckBox passwordCheckBox;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
